// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMM1AsxZdQbmmLF75MuqzTApxtIOG3jPU',
    appId: '1:874388073520:web:2c35f18f59b900632851f5',
    messagingSenderId: '874388073520',
    projectId: 'batch-13-26713',
    authDomain: 'batch-13-26713.firebaseapp.com',
    storageBucket: 'batch-13-26713.firebasestorage.app',
    measurementId: 'G-MQ04CFWE37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATrn-btdTbI5UPt-SB_HS4t6ENB-dZhDY',
    appId: '1:874388073520:android:52f138d7009b90982851f5',
    messagingSenderId: '874388073520',
    projectId: 'batch-13-26713',
    storageBucket: 'batch-13-26713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtq-DMwxi5hGZ-zeESmxmLhmJnphpSvXo',
    appId: '1:874388073520:ios:bc35a61e3c55e5732851f5',
    messagingSenderId: '874388073520',
    projectId: 'batch-13-26713',
    storageBucket: 'batch-13-26713.firebasestorage.app',
    androidClientId: '874388073520-0qfjf56es3q9e3nml8pr598okcqgd7nb.apps.googleusercontent.com',
    iosClientId: '874388073520-60tolr9f9u86bfv5r8ptstvcs1l08k5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.buisnessManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtq-DMwxi5hGZ-zeESmxmLhmJnphpSvXo',
    appId: '1:874388073520:ios:bc35a61e3c55e5732851f5',
    messagingSenderId: '874388073520',
    projectId: 'batch-13-26713',
    storageBucket: 'batch-13-26713.firebasestorage.app',
    androidClientId: '874388073520-0qfjf56es3q9e3nml8pr598okcqgd7nb.apps.googleusercontent.com',
    iosClientId: '874388073520-60tolr9f9u86bfv5r8ptstvcs1l08k5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.buisnessManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMM1AsxZdQbmmLF75MuqzTApxtIOG3jPU',
    appId: '1:874388073520:web:6fb552c24dfd0b852851f5',
    messagingSenderId: '874388073520',
    projectId: 'batch-13-26713',
    authDomain: 'batch-13-26713.firebaseapp.com',
    storageBucket: 'batch-13-26713.firebasestorage.app',
    measurementId: 'G-5GC0ZNQQZ1',
  );
}
