// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATwH8eWdAJVVKY-mqQPMMo7LeA4DVORoM',
    appId: '1:311926099600:web:4d1fef69f5a90c3dfc5215',
    messagingSenderId: '311926099600',
    projectId: 'buisness-manager-bc23f',
    authDomain: 'buisness-manager-bc23f.firebaseapp.com',
    storageBucket: 'buisness-manager-bc23f.firebasestorage.app',
    measurementId: 'G-JBCHLW7B2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBda295fWLsAqNaXoXvPmkgSgQ4teUsuoY',
    appId: '1:311926099600:android:88b7cb2b35384b72fc5215',
    messagingSenderId: '311926099600',
    projectId: 'buisness-manager-bc23f',
    storageBucket: 'buisness-manager-bc23f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5mzXEQlxG34Z51yUI91qLjNRhA1w-v50',
    appId: '1:311926099600:ios:59d9613bd9e8e2b8fc5215',
    messagingSenderId: '311926099600',
    projectId: 'buisness-manager-bc23f',
    storageBucket: 'buisness-manager-bc23f.firebasestorage.app',
    iosBundleId: 'com.example.buisnessManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5mzXEQlxG34Z51yUI91qLjNRhA1w-v50',
    appId: '1:311926099600:ios:59d9613bd9e8e2b8fc5215',
    messagingSenderId: '311926099600',
    projectId: 'buisness-manager-bc23f',
    storageBucket: 'buisness-manager-bc23f.firebasestorage.app',
    iosBundleId: 'com.example.buisnessManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATwH8eWdAJVVKY-mqQPMMo7LeA4DVORoM',
    appId: '1:311926099600:web:20c4f722417f5986fc5215',
    messagingSenderId: '311926099600',
    projectId: 'buisness-manager-bc23f',
    authDomain: 'buisness-manager-bc23f.firebaseapp.com',
    storageBucket: 'buisness-manager-bc23f.firebasestorage.app',
    measurementId: 'G-WL6XG54CPP',
  );
}
